name: "Generator"
on:
  workflow_dispatch:
    inputs:
      # https://github.com/clash-verge-rev/clash-verge-rev
      # net-proxy/clash-verge-rev/clash-verge-rev-2.5.1.ebuild
      # release artiface: ${PN}-${PV}-web.tar.xz: clash-verge-rev-2.5.1-web.tar.xz
      # release tag: ${P}=${PN}-${PV}: clash-verge-rev-2.5.1

      REPO:
        description: "github repo name: e.g. clash-verge-rev/clash-verge-rev"
        required: true

      TAG:
        description: "github tag: e.g. v2.5.1"
        required: true

      P:
        description: "P in ebuild: e.g. clash-verge-rev-2.5.1"
        required: true

      WORKDIR:
        description: "(optional) source directory to perform scripts"
        default: ''

jobs:
  Generator:
    permissions: write-all # required by push tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout input repo
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.REPO }}
          ref: ${{ inputs.TAG }}
          fetch-depth: 0

      - name: Generate timestamp
        id: timestamp
        run: |
          echo "BUILD_TIME=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: delete old tag
        env:
          P: ${{ inputs.P }}
          LANG: ${{ inputs.LANG }}
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag --delete ${P} || echo yes

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri dependencies
        run: |
          export NEEDRESTART_SUSPEND=1
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo -E apt-get install -y \
            libwebkit2gtk-4.1-dev libayatana-appindicator3-dev \
            librsvg2-dev patchelf xdg-utils

      - name: Run pnpm install
        run: pnpm install --frozen-lockfile

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          includeDebug: false

      - name: Compress dist to tar.xz
        run: |
          tar --create --auto-compress --file /tmp/${{ inputs.P }}-web.tar.xz ./dist
          ls -lh /tmp/${{ inputs.P }}-web.tar.xz

      - name: push tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true

      - name: upload golang deps to release artifaces
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ inputs.P }}
          body: |
            -tag: `${{ inputs.P }}`
            -Build Time: ${{ env.BUILD_TIME }}
          files: /tmp/${{ inputs.P }}-web.tar.xz
          tag_name: ${{ inputs.P }}
